services:
  bot:
    container_name: music_pipe_bot_container
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: musicpipebot/latest
    ports:
      - "8098:8080"
    networks:
      - musicpipe
    restart: unless-stopped

networks:
  musicpipe:
    driver: bridge